ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY HH24:MI:SS';
--TAIKHOAN
INSERT INTO TAIKHOAN(MATK, TENDN, MATKHAU, HOTEN, NGAYSINH, DIACHI, SDT, GMAIL, NGAYTAOTAIKHOAN, CHUCVU, LUONG) 
VALUES (SQ_TK.NEXTVAL, 'qly1', '123456', N'Nguy?n V?n A', '11-01-1999', N'43 Tân L?p, Ph??ng ?ông Hoà, D? An, Bình D??ng',  N'0111111111', N'a@gmail.com',  '12-01-2019', N'Qu?n lý', 40000);

INSERT INTO TAIKHOAN(MATK, TENDN, MATKHAU, HOTEN, NGAYSINH, DIACHI, SDT, GMAIL, NGAYTAOTAIKHOAN, CHUCVU, LUONG) 
VALUES (SQ_TK.NEXTVAL, 'qly2', '654321', N'Tr?n Th? B', '11-03-1999', N'44 Tân L?p, Ph??ng ?ông Hoà, D? An, Bình D??ng',  N'0111221111', N'b@gmail.com',  '12-01-2019', N'Qu?n lý', 45000);

INSERT INTO TAIKHOAN(MATK, TENDN, MATKHAU, HOTEN, NGAYSINH, DIACHI, SDT, GMAIL, NGAYTAOTAIKHOAN, CHUCVU, LUONG) 
VALUES (SQ_TK.NEXTVAL, 'nv1', '1234567', N'Hu?nh Th? C', '23-08-2003', N'45 Tân L?p, Ph??ng ?ông Hoà, D? An, Bình D??ng',  N'0333333333', N'c@gmail.com',  '28-02-2022', N'Nhân viên', 22000);

INSERT INTO TAIKHOAN(MATK, TENDN, MATKHAU, HOTEN, NGAYSINH, DIACHI, SDT, GMAIL, NGAYTAOTAIKHOAN, CHUCVU, LUONG) 
VALUES (SQ_TK.NEXTVAL, 'nv2', '1234568', N'Lung Th? Linh', '03-05-2002', N'34 ???ng S? 12, Ph??ng Tr??ng Th?, Th? ??c, TP HCM',  N'0122211111', N'linh@gmail.com',  '15-01-2021', N'Nhân viên', 25000);

INSERT INTO TAIKHOAN(MATK, TENDN, MATKHAU, HOTEN, NGAYSINH, DIACHI, SDT, GMAIL, NGAYTAOTAIKHOAN, CHUCVU, LUONG) 
VALUES (SQ_TK.NEXTVAL, 'nv3', '1234569', N'Lê V?n ?ô', '06-05-2002', N'43 ???ng S? 12, Ph??ng Tr??ng Th?, Th? ??c, TP HCM',  N'0122211133', N'do@gmail.com',  '18-08-2021', N'Nhân viên', 25000);

INSERT INTO TAIKHOAN(MATK, TENDN, MATKHAU, HOTEN, NGAYSINH, DIACHI, SDT, GMAIL, NGAYTAOTAIKHOAN, CHUCVU, LUONG) 
VALUES (SQ_TK.NEXTVAL, 'nv4', '1234570', N'Tr?n V?n D', '06-08-1999', N'16 Lê V?n Vi?t, Q9, TP HCM',  N'0123211133', N'D@gmail.com',  '18-08-2021', N'Nhân viên kho', 30000);

INSERT INTO TAIKHOAN(MATK, TENDN, MATKHAU, HOTEN, NGAYSINH, DIACHI, SDT, GMAIL, NGAYTAOTAIKHOAN, CHUCVU, LUONG) 
VALUES (SQ_TK.NEXTVAL, 'nv5', '1234670', N'?? V?n Nam', '06-10-1999', N'17 Nguy?n V?n T?ng, Q9, TP HCM',  N'0123222233', N'nam@gmail.com',  '18-09-2021', N'K? toán', 30000);

--KHACHHANG
INSERT INTO KHACHHANG(MAKH, HOTEN, NGAYSINH, SDT, DIACHI, CCCD, GIOITINH)
VALUES (SQ_KH.NEXTVAL, N'Nguy?n A', '07-07-1980',  N'0123456789', N'32 ???ng S? 3, Ph??ng Tr??ng Th?, Th? ??c, TP HCM ', '023456789111', N'Nam');

INSERT INTO KHACHHANG(MAKH, HOTEN, NGAYSINH, SDT, DIACHI, CCCD, GIOITINH)
VALUES (SQ_KH.NEXTVAL, N'Nguy?n B', '07-08-1980', N'0124456789', N'32  ???ng S? 3, Ph??ng Tr??ng Th?, Th? ??c, TP HCM', '023456799111', N'N?');

INSERT INTO KHACHHANG(MAKH, HOTEN, NGAYSINH, SDT, DIACHI, CCCD, GIOITINH)
VALUES (SQ_KH.NEXTVAL, N'Lê C', '17-08-1985', N'0124756789', N'14 ???ng S? 3, Ph??ng Tr??ng Th?, Th? ??c, TP HCM', '023456799222', N'N?');

INSERT INTO KHACHHANG(MAKH, HOTEN, NGAYSINH, SDT, DIACHI, CCCD, GIOITINH)
VALUES (SQ_KH.NEXTVAL, N'Tr?n Th? D', '20-06-1998', N'0384756789', N'244 Nguy?n Th??ng Hi?n, Ph??ng 6, Qu?n Bình Th?nh, TP HCM', '044335274136', N'N?');

INSERT INTO KHACHHANG(MAKH, HOTEN, NGAYSINH, SDT, DIACHI, CCCD, GIOITINH)
VALUES (SQ_KH.NEXTVAL, N'Tr?n V?n D', '22-06-2002', N'0358589888',  N'243A Nguy?n Th??ng Hi?n, Ph??ng 6, Qu?n Bình Th?nh, TP HCM', '053335274136', N'Nam');

--THELOAI
INSERT INTO THELOAI(MATL, TENTHELOAI) VALUES
(SQ_TL.NEXTVAL, N'Vi?n t??ng');

INSERT INTO THELOAI(MATL, TENTHELOAI) VALUES
(SQ_TL.NEXTVAL, N'Kinh d?');

INSERT INTO THELOAI(MATL, TENTHELOAI) VALUES
(SQ_TL.NEXTVAL, N'Phiêu l?u');

INSERT INTO THELOAI(MATL, TENTHELOAI) VALUES
(SQ_TL.NEXTVAL, N'Hài h??c');

INSERT INTO THELOAI(MATL, TENTHELOAI) VALUES
(SQ_TL.NEXTVAL, N'Thi?u nhi');

INSERT INTO THELOAI(MATL, TENTHELOAI) VALUES
(SQ_TL.NEXTVAL, N'Tâm lý');

--SACH
INSERT INTO SACH(MASACH, TENSACH, GIA, MATL, SLTON, TENTG, NXB, ANHSACH) VALUES
(SQ_S.NEXTVAL, N'??c nhân tâm', 86000, 6, 25, N'Dale Carnegie', N'NXB T?ng H?p TPHCM', N'\Book_img\dacnhantam.jpg');

INSERT INTO SACH(MASACH, TENSACH, GIA, MATL, SLTON, TENTG, NXB, ANHSACH) VALUES
(SQ_S.NEXTVAL, N'7 Thói quen ?? thành công', 118000, 6, 25, N'Stephen Covey', N'NXB Tr?', N'\Book_img\7thoiquendethanhcong.jpg');

INSERT INTO SACH(MASACH, TENSACH, GIA, MATL, SLTON, TENTG, NXB, ANHSACH) VALUES
(SQ_S.NEXTVAL, N'IT', 288000, 2, 25, N'Stephen King', N'NXB Thanh niên', N'\Book_img\IT.jpg');

INSERT INTO SACH(MASACH, TENSACH, GIA, MATL, SLTON, TENTG, NXB, ANHSACH) VALUES
(SQ_S.NEXTVAL, N'The Shining', 166000, 2, 5, N'Stephen King', N'NXB Thanh niên', N'\Book_img\theshining.jpg');

INSERT INTO SACH(MASACH, TENSACH, GIA, MATL, SLTON, TENTG, NXB, ANHSACH) VALUES
(SQ_S.NEXTVAL, N'Hai v?n d?m d??i ?áy bi?n', 67000, 3 , 5, N'Jules Verne', N'NXB Kim ??ng', N'\Book_img\haivandamduoidaybien.jpg');

INSERT INTO SACH(MASACH, TENSACH, GIA, MATL, SLTON, TENTG, NXB, ANHSACH) VALUES
(SQ_S.NEXTVAL, N'Nhà gi? kim', 69000, 3 , 10,  N'Paulo Coelho', N'NXB V?n H?c', N'\Book_img\nhagiakim.jpg');

INSERT INTO SACH(MASACH, TENSACH, GIA, MATL, SLTON, TENTG, NXB, ANHSACH) VALUES
(SQ_S.NEXTVAL, N'Ng??i truy?n kí ?c', 70000, 1 , 5,  N'Louis Lowry', N'NXB H?i V?n H?c', N'\Book_img\nguoitruyenkiuc.jpg');

INSERT INTO SACH(MASACH, TENSACH, GIA, MATL, SLTON, TENTG, NXB, ANHSACH) VALUES
(SQ_S.NEXTVAL, N'Ông tr?m tu?i trèo qua c?a s? và bi?n m?t', 164000, 4 , 5,  N'Jonas Jonasson', N'NXB Tr?', N'\Book_img\ongtramtuoi.jpg');

INSERT INTO SACH(MASACH, TENSACH, GIA, MATL, SLTON, TENTG, NXB, ANHSACH) VALUES
(SQ_S.NEXTVAL, N'Nh?ng Cu?c Phiêu L?u C?a Pinocchio', 114000, 5 , 5,  N'Carlo Collodi', N'NXB Dân Trí', N'\Book_img\pinochio.jpg');

--HOADON
INSERT INTO HOADON(MAHD, MAKH, MATK) VALUES 
(SQ_HD.NEXTVAL, NULL, 1);
 
INSERT INTO HOADON(MAHD, MAKH, MATK) VALUES 
(SQ_HD.NEXTVAL, 4, 1);

--CTHD
INSERT INTO CTHD(MAHD, MASACH, SOLUONG) VALUES
(1, 1, 5);

INSERT INTO CTHD(MAHD, MASACH, SOLUONG) VALUES
(1, 2, 5);

INSERT INTO CTHD(MAHD, MASACH, SOLUONG) VALUES
(2, 5, 5);

INSERT INTO CTHD(MAHD, MASACH, SOLUONG) VALUES
(2, 6, 5);

---NHACUNGCAP
INSERT INTO NHACUNGCAP(MANCC, TENNCC, DIACHI, SDT) VALUES
(SQ_NCC.NEXTVAL, N'Nhà sách Ph??ng nam', N'272 Lê Thánh Tôn, Ph??ng B?n Nghé, Q1, TPHCM', '0914129286');

INSERT INTO NHACUNGCAP(MANCC, TENNCC, DIACHI, SDT) VALUES
(SQ_NCC.NEXTVAL, N'Hi?u sách Nhã Nam', N'185 Hoa Lan, Ph??ng 2, Qu?n Phú Nhu?n, TPHCM', '0283847985');

--PHIEUNHAP
INSERT INTO PHIEUNHAP(MAPN, MANCC, MATK) VALUES
(SQ_PN.NEXTVAL, 1, 2);

INSERT INTO PHIEUNHAP(MAPN, MANCC, MATK) VALUES
(SQ_PN.NEXTVAL, 2, 1);

--CTPN
INSERT INTO CTPN(MAPN, MASACH, SOLUONGNHAP, GIANHAP) VALUES(1, 5, 40, 64000);
INSERT INTO CTPN(MAPN, MASACH, SOLUONGNHAP, GIANHAP) VALUES(1, 6, 30, 65000);

INSERT INTO CTPN(MAPN, MASACH, SOLUONGNHAP, GIANHAP) VALUES(2, 8, 15, 160000);
INSERT INTO CTPN(MAPN, MASACH, SOLUONGNHAP, GIANHAP) VALUES(2, 9, 15, 110000);

---CHAMCONG
INSERT INTO CHAMCONG(MATK, BATDAULAM, KETTHUC, SOGIOLAM) VALUES
(1, '20-05-2023 08:00:00',  '20-05-2023 16:00:00', 8);

INSERT INTO CHAMCONG(MATK, BATDAULAM, KETTHUC, SOGIOLAM) VALUES
(1, '22-05-2023 08:00:00',  '22-05-2023 16:00:00', 8);

---LUONG
INSERT INTO LUONG(MATK, THANG, NAM) VALUES
(1, 5, 2023);

