set serveroutput on;
--DOANH THU THEO THANG
CREATE OR REPLACE FUNCTION GET_DT_THANG (month_out NUMBER, year_out NUMBER) RETURN NUMBER
AS 
     dt NUMBER;
BEGIN
    SELECT SUM(TONGTIEN) INTO dt
    FROM HOADON
    WHERE EXTRACT(MONTH FROM NGAYTAOHD) = month_out
    AND EXTRACT(YEAR FROM NGAYTAOHD) = year_out;
    RETURN dt;
END;
/
--DOANH THU THEO NAM
CREATE OR REPLACE FUNCTION GET_DT_NAM (year_out NUMBER) RETURN NUMBER
AS 
     dt NUMBER;
BEGIN
    SELECT SUM(TONGTIEN) INTO dt
    FROM HOADON
    WHERE EXTRACT(YEAR FROM NGAYTAOHD) = year_out;
    RETURN dt;
END;
/
--TIEN NHAP THEO THANG
CREATE OR REPLACE FUNCTION GET_NHAP_THANG (month_out NUMBER, year_out NUMBER) RETURN NUMBER
AS 
     dt NUMBER;
BEGIN
    SELECT SUM(TONGTIENNHAP) INTO dt
    FROM PHIEUNHAP
    WHERE EXTRACT(MONTH FROM NGAYNHAP) = month_out
    AND EXTRACT(YEAR FROM NGAYNHAP) = year_out;
    RETURN dt;
END;
/
--TIEN NHAP THEO NAM
CREATE OR REPLACE FUNCTION GET_NHAP_NAM (year_out NUMBER) RETURN NUMBER
AS 
     dt NUMBER;
BEGIN
    SELECT SUM(TONGTIENNHAP) INTO dt
    FROM PHIEUNHAP
    WHERE EXTRACT(YEAR FROM NGAYNHAP) = year_out;
    RETURN dt;
END;