--SEQUENCE
CREATE SEQUENCE SQ_TK START WITH 1;
CREATE SEQUENCE SQ_S START WITH 1;
CREATE SEQUENCE SQ_HD START WITH 1;
CREATE SEQUENCE  SQ_TL START WITH 1;
CREATE SEQUENCE SQ_NCC START WITH 1;
CREATE SEQUENCE SQ_PN START WITH 1;
CREATE SEQUENCE SQ_KH START WITH 1;

